"""add_email_addresses_table

Revision ID: 22dad42c8d24
Revises: 3b6d750552da
Create Date: 2026-01-09 21:43:43.550694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import Uuid


# revision identifiers, used by Alembic.
revision: str = '22dad42c8d24'
down_revision: Union[str, Sequence[str], None] = '3b6d750552da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_addresses',
    sa.Column('id', Uuid(as_uuid=True), nullable=False),
    sa.Column('contact_id', Uuid(as_uuid=True), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_address_contact', 'email_addresses', ['contact_id'], unique=False)
    op.create_index('idx_email_address_value', 'email_addresses', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_email_address_value', table_name='email_addresses')
    op.drop_index('idx_email_address_contact', table_name='email_addresses')
    op.drop_table('email_addresses')
    # ### end Alembic commands ###
