"""Initial schema

Revision ID: 3b6d750552da
Revises: 
Create Date: 2026-01-04 06:15:46.415818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from google_contacts_cisco.models import GUID


# revision identifiers, used by Alembic.
revision: str = '3b6d750552da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contact_display_name', 'contacts', ['display_name'], unique=False)
    op.create_index('idx_contact_resource_name', 'contacts', ['resource_name'], unique=False)
    op.create_index(op.f('ix_contacts_display_name'), 'contacts', ['display_name'], unique=False)
    op.create_index(op.f('ix_contacts_resource_name'), 'contacts', ['resource_name'], unique=True)
    op.create_table('sync_states',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('sync_token', sa.String(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_numbers',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('contact_id', GUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('display_value', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_phone_number_contact', 'phone_numbers', ['contact_id'], unique=False)
    op.create_index('idx_phone_number_value', 'phone_numbers', ['value'], unique=False)
    op.create_index(op.f('ix_phone_numbers_value'), 'phone_numbers', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_numbers_value'), table_name='phone_numbers')
    op.drop_index('idx_phone_number_value', table_name='phone_numbers')
    op.drop_index('idx_phone_number_contact', table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_table('sync_states')
    op.drop_index(op.f('ix_contacts_resource_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_display_name'), table_name='contacts')
    op.drop_index('idx_contact_resource_name', table_name='contacts')
    op.drop_index('idx_contact_display_name', table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
